language: node_js
node_js:
  - "0.10"

before_install:
  - "npm install codeclimate-test-reporter"
  - "npm install karma-cli"

before_script:
  - npm install bower
  - bower install

script:
  - npm test

after_script:
  - codeclimate < ./coverage/PhantomJS\ 1.9.8\ \(Windows\ 8\)/lcov.info

addons:
  code_climate:
    repo_token: ef2fe2e0aa88431f512290dcbfe6d43a4fb78e7a538e8a097d69459a1c499d99